[package]
name = "ferrum-ui"
version = "0.1.0"
edition = "2024"

[dependencies]
#ash = "0.38.0"
#egui = "0.32.0"
#gpu-allocator = { version = "0.27.0", features = ["vulkan"] }
#winit = { version = "0.29", features = ["rwh_06"] }
