[workspace]
members = [
    "crates/ferrum-scene",
    "crates/ferrum-physics",
    "crates/ferrum-assets",
    "crates/ferrum-render",
    "crates/ferrum-cli",
    "crates/ferrum-graph",
    "crates/ferrum-sound",
    "crates/ferrum-ui",
    "crates/editor-standalone",
    "crates/ferrum-resources",
    "crates/ferrum-math",
    "crates/ferrum-shapes",
    "crates/ferrum-types",
    "crates/ferrum-net",
    "examples/cube",
]
resolver = "2"

