[package]
name = "cube"
version = "0.1.0"
edition = "2024"
#build = "build.rs"

[dependencies]
ash = { version = "0.38.0",  features = ["debug", "std"] }
ash-window = "0.13.0"
egui = "0.32.1"
egui-winit = "0.32.1"
egui_extras = { version = "0.32.1", default-features = false, features = ["all_loaders"] }
winit = { version = "0.29", features = ["rwh_06"] }
log = "0.4"
env_logger = { version = "0.11.8", features = ["color"] }
cfg-if = { version = "1" }
image = { version = "0.25.6", features = ["png", "jpeg"] }
ferrum-render = { path = "../../crates/ferrum-render" }
ferrum-types = { path = "../../crates/ferrum-types" }
ferrum-graph = { path = "../../crates/ferrum-graph" }
ferrum-net = { path = "../../crates/ferrum-net" }
#ferrum-physics = { path = "../../crates/ferrum-physics" }
ferrum-assets = { path = "../../crates/ferrum-assets" }
ferrum-ui = { path = "../../crates/ferrum-ui" }
ferrum-resources = { path = "../../crates/ferrum-resources" }
glam = "*"
raw-window-handle = "0.6.2"
tracing-subscriber = { version = "0.3.20", features = ["fmt"] }
tracing.workspace = true
mlua = { version = "0.11.3", features = ["vendored", "lua54"] }

