[package]
name = "ferrum-sound"
version = "0.1.0"
edition = "2024"
authors = ["Oleg Pavlenko"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/olejaaaaaaaa/ferrum/crates/ferrum-sound"

[dependencies]
cpal = { version = "0.16.0", features = ["asio"] }
