[package]
name = "ferrum-physics"
version = "0.1.0"
edition = "2024"
authors = ["Oleg Pavlenko"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/olejaaaaaaaa/ferrum/crates/ferrum-physics"

[dependencies]
rapier3d = "0.28.0"
