[package]
name = "ferrum-resources"
version = "0.1.0"
edition = "2024"
authors = ["Oleg Pavlenko"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/olejaaaaaaaa/ferrum/crates/ferrum-resources"

[dependencies]
ash = { version = "0.38.0",  features = ["debug", "std"] }